[[redirects]]
  from = "https://olivermak.es/*"
  to = "https://oliverpattison.com/"
  status = 301
  
[[redirects]]
  from = "https://www.olivermak.es/*"
  to = "https://oliverpattison.com/"
  status = 301
  
[[ redirects ]]
  from = "https://oliverpattison.netlify.com/*"
  to = "https://oliverpattison.com/"
  status = 301
  force = true