[[redirects]]
  from = "https://olivermak.es/*"
  to = "https://oliverpattison.com/"
  status = 301
  force = true
  
[[redirects]]
  from = "https://www.olivermak.es/*"
  to = "https://oliverpattison.com/"
  status = 301
  force = true
  
[[ redirects ]]
  from = "https://oliverpattison.netlify.com/*"
  to = "https://oliverpattison.com/"
  status = 301
  force = true
  
[[ redirects ]]
  from = "/stories/:splat"
  to = "/:splat"
  status = 301
  
[[ redirects ]]
  from = "/stories/"
  to = "/projects/"
  status = 301

[[headers]]
  for = "/fonts/*.woff2"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Content-Type = "font/woff2"